---
sidebar: sidebar 
permalink: reference-storage-limits.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos. 
---
= Limites de armazenamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP tem limites de configuração de storage para fornecer operações confiáveis. Para obter o melhor desempenho, não configure o sistema com os valores máximos.



== Capacidade máxima do sistema por licença

A capacidade máxima do sistema para um sistema Cloud Volumes ONTAP é determinada pela sua licença. A capacidade máxima do sistema inclui storage baseado em disco e storage de objetos usado para categorização de dados. O NetApp não suporta exceder esse limite.

No Azure, os limites de disco impedem que você alcance o limite de capacidade de 368 TIB usando discos sozinhos. Nesses casos, você pode alcançar o limite de capacidade de 368 TIB em https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["disposição em camadas dos dados inativos no storage de objetos"^]. <<Limites de capacidade e disco pelo tamanho da VM do Azure,Limites de capacidade e disco pelo tamanho da VM do Azure>>Consulte para obter mais detalhes.

[cols="30,70"]
|===
| Licença | Capacidade máxima do sistema (discos e armazenamento de objetos) 


| Explore | 2 TIB (disposição de dados em categorias não é compatível com o Explore) 


| Padrão | 10 TIB 


| Premium | 368 TIB 


| BYOL | 368 TIB por licença 
|===
.No caso de HA, o limite de capacidade da licença por nó ou para todo o par de HA?
O limite de capacidade aplica-se a todo o par de HA. Não é por nó. Por exemplo, se você usar a licença Premium, poderá ter até 368 TIB de capacidade entre os dois nós.

.Para um sistema de HA na AWS, os dados espelhados contam com limite de capacidade?
Não, não. Os dados em um par de HA da AWS são espelhados de forma síncrona entre os nós para que os dados estejam disponíveis em caso de falha. Por exemplo, se você comprar um disco TIB de 8 TB no nó A, o Cloud Manager também aloca um disco TIB de 8 TB no nó B usado para dados espelhados. Embora 16 TIB de capacidade tenha sido provisionado, apenas 8 TIB conta contra o limite de licença.



== Limites de agregado e disco para o Cloud Volumes ONTAP na AWS

No Cloud Volumes ONTAP 9,4, todos os tipos de instâncias do EC2 podem alcançar o limite de capacidade TIB de 368 TB usando o armazenamento EBS sozinho ou usando armazenamento EBS e disposição em camadas para S3 TB (nó único e HA).

[cols="3*"]
|===
| Armazenamento físico | Parâmetro | Limite 


.5+| *Agregados e discos* | Número máximo de agregados | 34 para configurações de nó único 18 por nó em uma configuração de HA 1 


| Tamanho máximo de agregado | 96 TIB de capacidade bruta 2 


| Discos por agregado | 1-6 3 


| Tamanho máximo do disco | 16 TIB 


| Número máximo de discos de dados em todos os agregados 4 | 34 para configurações de nó único, 31 por nó em uma configuração de HA 


| *Grupos RAID* | Máximo por agregado | 1 
|===
Notas:

. Não é possível criar agregados 18 em ambos os nós em um par de HA, pois isso excederia o limite do disco de dados.
. O limite de capacidade agregada é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Todos os discos em um agregado devem ter o mesmo tamanho.
. O limite do disco de dados é específico para discos que contêm dados do usuário. O disco de inicialização e o disco raiz para cada nó não estão incluídos neste limite.




== Limites de agregado e disco para Cloud Volumes ONTAP no Azure

[cols="3*"]
|===
| Armazenamento físico | Parâmetro | Limite 


.5+| *Agregados e discos* | Número máximo de agregados | O mesmo que o limite do disco 


| Tamanho máximo de agregado | 200 TIB de capacidade bruta 1 


| Discos por agregado | 1-12 2 


| Tamanho máximo do disco | 32 TIB 


| Número máximo de discos de dados em todos os agregados 3 | Depende do tamanho da VM. <<Limites de capacidade e disco pelo tamanho da VM do Azure,Veja abaixo>>. 


| *Grupos RAID* | Máximo por agregado | 1 
|===
Notas:

. O limite de capacidade agregada é baseado nos discos que compõem o agregado. O limite não inclui o storage de objetos usado para categorização de dados.
. Todos os discos em um agregado devem ter o mesmo tamanho.
. O limite do disco de dados é específico para discos que contêm dados do usuário. O disco de inicialização e o disco raiz para cada nó não estão incluídos neste limite.




=== Limites de capacidade e disco pelo tamanho da VM do Azure

No Azure, os sistemas de nó único podem usar discos gerenciados HDD padrão, discos gerenciados SSD padrão e discos gerenciados SSD Premium, com até 32 TIB por disco. O número de discos suportados varia de acordo com o tamanho da VM.

As tabelas abaixo mostram a capacidade máxima do sistema por tamanho da VM somente com discos e com a disposição em camadas de discos e dados inativos no storage de objetos.

Os limites de disco são mostrados pelo tamanho da VM para licenças Premium e BYOL apenas porque os limites de disco não podem ser alcançados com licenças Explore ou Standard devido aos limites de capacidade do sistema.



==== Nó único com licença Premium

[cols="14,20,31,33"]
|===
| Tamanho da VM | Máximo de discos por nó | Capacidade máxima do sistema somente com discos | Capacidade máxima do sistema com discos e categorização de dados 


| DS3_v2 | 15 | 368 TIB | Disposição em camadas não compatível 


| DS4_v2 | 31 | 368 TIB | 368 TIB 


| DS5_v2 | 63 | 368 TIB | 368 TIB 


| DS13_v2 | 31 | 368 TIB | 368 TIB 


| DS14_v2 | 63 | 368 TIB | 368 TIB 
|===


==== Nó único com uma ou mais licenças BYOL


NOTE: Para alguns tipos de VM, você precisará de várias licenças BYOL para alcançar a capacidade máxima do sistema listada abaixo. Por exemplo, você precisaria de 6 licenças BYOL para alcançar 2 PIB com DS5_v2.

[cols="10,18,18,18,18,18"]
|===
| Tamanho da VM | Máximo de discos por nó 2+| Capacidade máxima do sistema com uma licença 2+| Capacidade máxima do sistema com várias licenças 


2+|  | *Discos sozinhos* | *Discos e categorização de dados* | *Discos sozinhos* | *Discos e categorização de dados* 


| DS3_v2 | 15 | 368 TIB | Disposição em camadas não compatível | 480 TIB | Disposição em camadas não compatível 


| DS4_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x cada licença 


| DS5_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x cada licença 


| DS13_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x cada licença 


| DS14_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x cada licença 
|===


== Limites lógicos de armazenamento

[cols="22,22,56"]
|===
| Storage lógico | Parâmetro | Limite 


| *Storage Virtual Machines (SVMs)* | Número máximo de Cloud Volumes ONTAP (par de HA ou nó único) | Um SVM de fornecimento de dados e um SVM de destino usado na recuperação de desastres. Você pode ativar o SVM de destino para acesso aos dados se houver uma interrupção na SVM de origem. 1 o único SVM de fornecimento de dados abrange todo o sistema Cloud Volumes ONTAP (par de HA ou nó único). 


.2+| *Ficheiros* | Tamanho máximo | 16 TIB 


| Máximo por volume | Depende do tamanho do volume, até 2 bilhões 


| *Volumes FlexClone* | Profundidade do clone hierárquico 2 | 499 


.3+| *Volumes FlexVol* | Máximo por nó | 500 


| Tamanho mínimo | 20 MB 


| Tamanho máximo | AWS: Dependente do tamanho do agregado 3 Azure: 100 TIB 


| *Qtrees* | Máximo por FlexVol volume | 4.995 


| *Cópias Snapshot* | Máximo por FlexVol volume | 1.023 
|===
Notas:

. O Cloud Manager não oferece nenhuma configuração ou suporte de orquestração para a recuperação de desastres da SVM. Ele também não dá suporte a tarefas relacionadas a storage em uma SVM adicional. Use o System Manager ou a CLI para recuperação de desastres da SVM.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guia expresso de preparação para recuperação de desastres da SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guia do SVM Disaster Recovery Express"^]


. Profundidade de clone hierárquica é a profundidade máxima de uma hierarquia aninhada de volumes FlexClone que pode ser criada a partir de um único FlexVol volume.
. Menos de 100 TIB é suportado porque os agregados para essa configuração estão limitados a 96 TIB de capacidade _bruta_.




== Limites de armazenamento iSCSI

[cols="3*"]
|===
| Armazenamento iSCSI | Parâmetro | Limite 


.4+| *LUNs* | Máximo por nó | 1.024 


| Número máximo de mapas LUN | 1.024 


| Tamanho máximo | 16 TIB 


| Máximo por volume | 512 


| *grupos* | Máximo por nó | 256 


.2+| *Iniciadores* | Máximo por nó | 512 


| Máximo por grupo | 128 


| * Sessões iSCSI* | Máximo por nó | 1.024 


.2+| *LIFs* | Máximo por porta | 32 


| Máximo por portset | 32 


| *Portsets* | Máximo por nó | 256 
|===